### ISSUE TITLE
java.lang.NoSuchMethodError: No static method encodeHexString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/ext.jar)

### ISSUE THREAD

**Issue by kaviyarasu1987** [Red5/red5-client#46]
Run time Exception occurs in android in built libraries android studio which contains its own recent apache codec if we add through gradle

**Comment by kaviyarasu1987** [comment]
compile group: 'org.red5', name: 'red5-client', version: '1.1.1'

**Comment by kaviyarasu1987** [comment]
Full details here

    java.lang.NoSuchMethodError: No static method encodeHexString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/ext.jar)
        at org.red5.client.net.rtmp.OutboundHandshake.generateClientRequest1(OutboundHandshake.java:176)
        at org.red5.client.net.rtmp.RTMPMinaIoHandler.sessionOpened(RTMPMinaIoHandler.java:99)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.sessionOpened(DefaultIoFilterChain.java:930)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionOpened(DefaultIoFilterChain.java:565)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$800(DefaultIoFilterChain.java:48)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionOpened(DefaultIoFilterChain.java:1069)
        at org.apache.mina.core.filterchain.IoFilterAdapter.sessionOpened(IoFilterAdapter.java:89)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionOpened(DefaultIoFilterChain.java:565)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$800(DefaultIoFilterChain.java:48)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionOpened(DefaultIoFilterChain.java:1069)
        at org.apache.mina.core.filterchain.IoFilterAdapter.sessionOpened(IoFilterAdapter.java:89)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionOpened(DefaultIoFilterChain.java:565)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireSessionOpened(DefaultIoFilterChain.java:558)
        at org.apache.mina.core.service.IoServiceListenerSupport.fireSessionCreated(IoServiceListenerSupport.java:219)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.addNow(AbstractPollingIoProcessor.java:838)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.handleNewSessions(AbstractPollingIoProcessor.java:752)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:652)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by mondain** [comment]
The **Hex** in this case is `org.bouncycastle.util.encoders.Hex` you'll need to add bouncy castle.
